### PR TITLE
Use normalized icon for edit dialog and for reset purposes

### PR DESCRIPTION
**Pull request by enricocid**
getDrawableIconForPackage(component) gets the default app icon not normalized. So if You reset an app's icon You'll get a bigger one than the others.
This way You'll get the "badged"icon that is the one used for the apps.

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
Hey,
We don't accept pull requests, so would be cool if you could push
this to gerrit.aospa.co so we can review it.

**Comment by enricocid** [comment]
unfortunately I don't have a pc running a gnu-linux distribution:(

**Comment by TheCrazyLex** [comment]
If git push works, it is possible to push to gerrit :)

**Comment by enricocid** [comment]
done! but I don't know if i did it right!:)

**Comment by enricocid** [comment]
Hi Alex,
I read the messages on Gerrit yesterday. Unfortunately actually I'm out for a vacation and I don't have my pc with me. I will be back next Thursday:)

**Pull request closed without merging**
